-- CreateTable
CREATE TABLE "Assessment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "contactName" TEXT NOT NULL,
    "contactEmail" TEXT NOT NULL,
    "contactPhone" TEXT,
    "companyName" TEXT NOT NULL,
    "companyProfile" JSONB NOT NULL,
    "departments" JSONB,
    "techStack" JSONB,
    "dataReadiness" JSONB,
    "aiAdoption" JSONB,
    "automation" JSONB,
    "agentInterest" JSONB,
    "security" JSONB,
    "employeeReadiness" JSONB,
    "categoryScores" JSONB NOT NULL,
    "totalScore" INTEGER NOT NULL,
    "stage" TEXT NOT NULL,
    "dataCompleteness" TEXT,
    "benchmark" JSONB,
    "swot" JSONB,
    "opportunityMatrix" JSONB,
    "risk" JSONB,
    "roadmap" JSONB,
    "roi" JSONB,
    "executiveSummary" TEXT
);
